name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        scala: ['2.12', '2.13']
        java: ['8', '11']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        id: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
          cache: sbt

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Update dependencies
        if: steps.setup-java.outputs.cache-hit == 'false'
        run: sbt +update

      - name: Compile and check format
        run: >-
          sbt ++${{ matrix.scala }} Test/compile scalafmtSbt &&
          git diff --exit-code

      - name: Run tests
        run: sbt ++${{ matrix.scala }} "set concurrentRestrictions in Global := Seq(Tags.limit(Tags.Test, 1))" coverage test

      - name: Build Scaladoc
        run: sbt ++${{ matrix.scala }} doc
